 
steps:
  - name: Test & publish code coverage
    uses: paambaati/codeclimate-action@v2.7.5
    env:
      CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
    with:
      coverageCommand: coverage run --source='src/pages/' tests/manage.py test && coverage report
      debug: true
